import { atom } from 'jotai'
export const requestDataAtom = atom({
  proNo: null,
  storage: null,
  spart: null,
  stockStatus: null,
  supplier: null,
  preferThickNess: null,
  grade: null,
  maker: null,
  spec: null,
  minThickness: null,
  maxThickness: null,
  minWidth: null,
  maxWidth: null,
  minLength: null,
  maxLength: null,
  minFailCount: null,
  maxFailCount: null,
  saleCategoryList: null,
  saleType: null,
  salePriceType: null,
  productNumberList: null,
})
