import { useState } from 'react'
import { CheckBoxDefault } from '../storeCheckbox'

/** 셀의 내용을 지정할 수 있는 columnDefs */
export const getColumnDefs = (data, setData) => [
  {
    headerName: '✅',
    field: 'check',
    headerClass: 'custom-header-style',
    cellStyle: { borderRight: '1px solid #c8c8c8' },
    width: 50,
    cellRenderer: () => {
      return <input type="checkbox" />
    },
  },
  {
    headerName: '순번',
    field: 'num',
    headerClass: 'custom-header-style',
    cellStyle: { borderRight: '1px solid #c8c8c8' },
    width: 80,
    cellRenderer: (params) => params.value || 'N/A',
  },
  {
    headerName: '경매 / 상시 판매 번호',
    field: 'auctionNumber',
    headerClass: 'custom-header-style',
    cellStyle: { borderRight: '1px solid #c8c8c8' },
    width: 160,
    cellRenderer: (params) => params.value || 'N/A',
  },
  {
    headerName: '주문 일자',
    field: 'orderDate',
    headerClass: 'custom-header-style',
    cellStyle: { borderRight: '1px solid #c8c8c8' },
    width: 107,
    cellRenderer: (params) => params.value || 'N/A',
  },
  {
    headerName: '패키지 명',
    field: 'packageName',
    headerClass: 'custom-header-style',
    cellStyle: { borderRight: '1px solid #c8c8c8' },
    width: 100,
    cellRenderer: (params) => params.value || 'N/A',
  },
  {
    headerName: '패키지 번호',
    field: 'packageNumber',
    headerClass: 'custom-header-style',
    cellStyle: { borderRight: '1px solid #c8c8c8' },
    width: 120,
    cellRenderer: (params) => params.value || 'N/A',
  },
  {
    headerName: '주문 상태',
    field: 'title',
    headerClass: 'custom-header-style',
    cellStyle: { borderRight: '1px solid #c8c8c8' },
    width: 100,
    cellRenderer: (params) => params.value || 'N/A',
  },
  {
    headerName: '확정전송 일자',
    field: 'title',
    headerClass: 'custom-header-style',
    cellStyle: { borderRight: '1px solid #c8c8c8' },
    width: 125,
    cellRenderer: (params) => params.value || 'N/A',
  },
  {
    headerName: '주문 번호',
    field: 'orderNumber',
    headerClass: 'custom-header-style',
    cellStyle: { borderRight: '1px solid #c8c8c8' },
    width: 110,
    cellRenderer: (params) => params.value || 'N/A',
  },
  {
    headerName: '고객사 명',
    field: 'customerName',
    headerClass: 'custom-header-style',
    cellStyle: { borderRight: '1px solid #c8c8c8' },
    width: 150,
    cellRenderer: (params) => params.value || 'N/A',
  },
  {
    headerName: '고객 코드',
    field: 'customerCode',
    headerClass: 'custom-header-style',
    cellStyle: { borderRight: '1px solid #c8c8c8' },
    width: 150,
    cellRenderer: (params) => params.value || 'N/A',
  },
  {
    headerName: '창고',
    field: 'storageName',
    headerClass: 'custom-header-style',
    cellStyle: { borderRight: '1px solid #c8c8c8' },
    width: 90,
    cellRenderer: (params) => params.value || 'N/A',
  },
  {
    headerName: '판매 구분',
    field: 'title',
    headerClass: 'custom-header-style',
    cellStyle: { borderRight: '1px solid #c8c8c8' },
    width: 120,
    cellRenderer: (params) => params.value || 'N/A',
  },
  {
    headerName: '판매 유형',
    field: 'saleType',
    headerClass: 'custom-header-style',
    cellStyle: { borderRight: '1px solid #c8c8c8' },
    width: 120,
    cellRenderer: (params) => params.value || 'N/A',
  },
  {
    headerName: '판매가 유형',
    field: 'salePriceType',
    headerClass: 'custom-header-style',
    cellStyle: { borderRight: '1px solid #c8c8c8' },
    width: 120,
    cellRenderer: (params) => params.value || 'N/A',
  },
  {
    headerName: '경매 번호',
    field: 'auctionNumber',
    headerClass: 'custom-header-style',
    cellStyle: { borderRight: '1px solid #c8c8c8' },
    width: 120,
    cellRenderer: (params) => params.value || 'N/A',
  },
  {
    headerName: '상시 판매 번호',
    field: 'salePriceType',
    headerClass: 'custom-header-style',
    cellStyle: { borderRight: '1px solid #c8c8c8' },
    width: 120,
    cellRenderer: (params) => params.value || 'N/A',
  },
  {
    headerName: '상시 판매',
    field: 'salePriceType',
    headerClass: 'custom-header-style',
    cellStyle: { borderRight: '1px solid #c8c8c8' },
    width: 120,
    cellRenderer: (params) => params.value || 'N/A',
  },
  {
    headerName: '주문 일자',
    field: 'createDate',
    headerClass: 'custom-header-style',
    cellStyle: { borderRight: '1px solid #c8c8c8' },
    width: 120,
    cellRenderer: (params) => params.value || 'N/A',
  },
  {
    headerName: '주문 상태',
    field: 'salePriceType',
    headerClass: 'custom-header-style',
    cellStyle: { borderRight: '1px solid #c8c8c8' },
    width: 120,
    cellRenderer: (params) => params.value || 'N/A',
  },
  {
    headerName: '확정전송 일자',
    field: 'updateDate',
    headerClass: 'custom-header-style',
    cellStyle: { borderRight: '1px solid #c8c8c8' },
    width: 120,
    cellRenderer: (params) => params.value || 'N/A',
  },
  {
    headerName: '주문 번호',
    field: 'salePriceType',
    headerClass: 'custom-header-style',
    cellStyle: { borderRight: '1px solid #c8c8c8' },
    width: 120,
    cellRenderer: (params) => params.value || 'N/A',
  },
  {
    headerName: '고객사 명',
    field: 'salePriceType',
    headerClass: 'custom-header-style',
    cellStyle: { borderRight: '1px solid #c8c8c8' },
    width: 120,
    cellRenderer: (params) => params.value || 'N/A',
  },
  {
    headerName: '고객 코드',
    field: 'salePriceType',
    headerClass: 'custom-header-style',
    cellStyle: { borderRight: '1px solid #c8c8c8' },
    width: 120,
    cellRenderer: (params) => params.value || 'N/A',
  },
  {
    headerName: '제품 번호',
    field: 'salePriceType',
    headerClass: 'custom-header-style',
    cellStyle: { borderRight: '1px solid #c8c8c8' },
    width: 120,
    cellRenderer: (params) => params.value || 'N/A',
  },
  {
    headerName: 'ProNo.',
    field: 'salePriceType',
    headerClass: 'custom-header-style',
    cellStyle: { borderRight: '1px solid #c8c8c8' },
    width: 120,
    cellRenderer: (params) => params.value || 'N/A',
  },
]
